# Generated by Django 5.2.3 on 2025-06-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_personal_info_alter_resume_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
