# Generated by Django 5.2.3 on 2025-07-02 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_resume_created_at'),
    ]

    operations = [
    ]
